AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Sample to create an S3 bucket and an EC2 instance

Parameters:
  BucketName:
    Type: String
    Description: Unique name for the S3 bucket
    Default: my-sample-s3-bucket-unique

  EC2InstanceType:
    Type: String
    Description: EC2 Instance Type
    Default: t2.micro
   
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance

  AMIId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID for the EC2 instance
    Default: ami-0acakgdef12345936

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIId
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref KeyPairName
      SecurityGroups:
        - Ref: InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket
    Value: !Ref MyS3Bucket

  EC2InstanceId:
    Description: ID of the created EC2 instance
    Value: !Ref MyEC2Instance

